#spring.cloud.zookeeper.config.enable=true;
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
spring:
  application:
    name: lxcloudapi
  #注册中心的地址
