spring:
  application:
    name: lxvideoprovider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_selfcoding1807?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册中心的地址
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
server:
  port: 8084

